### ISSUE TITLE
graphql.web does not support tree shaking

### ISSUE THREAD

**Issue by ktmouk** [0no-co/graphql.web#37]
### Describe the bug

Thank you for making great library!

I noticed that unused GraphQL documents are included in the build files when I use `gql.tada` + `urql` + `Next.js@15`.
This behavior is inconvenient when importing files from barrel files as all unused graphql document are built whenever they are used or not.

I think it is due to [idx and input](https://github.com/0no-co/graphql.web/blob/0e92930450593655f0fd6fd3ad993e913f7a74f9/src/parser.ts#L13) variables are defined outside of functions. Although I haven't come up with a good way to fix this yet, I’d be happy to contribute if you agree that it should be fixed.

### workaround

We can indicate to the bundler that `graphql()` is tree-shakable by adding `/*#__PURE__*/`.

```ts
export const unusedQuery = /*#__PURE__*/ graphql(`query unusedQuery { __typename }`)
```

### Reproduction

https://github.com/ktmouk/tree-shaking-gql-web

### Package version

- @0no-co/graphql.web@0.1.0

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which GitHub Discussions should be used
- [X] Follow our [Code of Conduct](https://github.com/0no-co/graphql.web/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
Tree-shaking doesn't do what you assume it does, see for example:
- https://github.com/evanw/esbuild/issues/1241
- https://webpack.js.org/guides/tree-shaking/

Just because a module is marked as `"sideEffects": false`, for example, and its imports are unused does not mean that its exports are side-effect free. It means that a module as a whole (in this case the package) can be dropped if it's unused.

However, Rollup would not, for example, perform any analysis of an externalised module, like in your example repo, and determine whether a function is side-effect-free. To go further, even adding comment hints to module code has a really high build performance penalty in most cases, so libraries don't include these a lot (and they're often not taken into account by bundlers in packages anyway because of this)

But to keep it short and to your issue: Rollup does not consider external modules as **pure** just based on the usage of exports and the `sideEffects` marker alone, no matter if variables are used or not, see: https://rollupjs.org/configuration-options/#treeshake-modulesideeffects

On a side-note, `0.1.0` is an invalid release version of `@0no-co/graphql.web` as per the changelog: https://github.com/0no-co/graphql.web/blob/main/CHANGELOG.md
